### ISSUE TITLE
Add reputation system to Discord server

### ISSUE THREAD

**Issue by EricPickup** [uwindsorcss/css-discord-bot#1]
We should add a reputation system aiming to bring up user engagement.

At GitHub we have something called "sparkling" where you can type `.sparkle @username` and it will announce that that person has received a sparkle and post the amount of points they now have.

You do this whenever someone does anything significant (i.e. makes something cool, helps someone, etc.).

We could post the top stats weekly.

**Comment by amanpatel123** [comment]
This one is a very exciting feature. Just curious, how is this one going?

**Comment by EricPickup** [comment]
@amanpatel123 practically done, just gotta find the time to look it all over and push the changes
