### ISSUE TITLE
Replace `~year` with a reaction system

### ISSUE THREAD

**Issue by prairir** [uwindsorcss/css-discord-bot#24]
#### Describe Problem
`~year` is unintuitive and unknown to some people.
#### Suggest Solution
a post in a channel that people would react to get their year role
#### Additional Details
this is more difficult because you have to unreact the user from some of them.
for example. if the user reacts to `year 1` and they are already reacted to `year 2` you have to unreact and remove the role from them.

**Comment by BorhanSaflo** [comment]
This is now natively supported by Discord through the Community Onboarding Tool.

https://support.discord.com/hc/en-us/articles/11074987197975-Community-Onboarding-FAQ
