### ISSUE TITLE
Add edit command

### ISSUE THREAD

**Issue by prairir** [uwindsorcss/css-discord-bot#41]
#### Describe Problem
There is no edit command
#### Suggest Solution
add an edit command
#### Additional Details
the edit command takes in a message link or ID as a param
text to change message to as another param

and edits the original linked message to the new text.

**Comment by kilbouri** [comment]
Assuming this refers to messages created by anyone, this cannot be done (to my knowledge, anyways). Editing other users' messages is forbidden.

**Comment by prairir** [comment]
Yes i didnt specify what exactly i meant. I mean editing bot messages
