### ISSUE TITLE
quick link command

### ISSUE THREAD

**Issue by prairir** [uwindsorcss/css-discord-bot#58]
#### Describe Problem
We need a way to have quick links to guides or resources for students. Many students ask the same questions with out searching or googling. TBH its very annoying.
#### Suggest Solution
A quick link command. 

basically a command to fetch quick links.

It needs to be 
* dynamic
* persistent(we would like this hooked up to a db)
* quick to use
* with modern slash commands

The commands would be something like `/link`
with subcommands 
* `set <key> <value>`  to set with key and value
* `get <key>` to get `<value>`
* `list` to show all current quick links

#### Additional Details
The db should be sqlite in dev mode and postgres in prod mode

**Comment by prairir** [comment]
I forgot to mention, pls dont use ORMs or anything fancy. simple raw sql will work fine as long as were using prepared statements with good sanitization

**Comment by kilbouri** [comment]
We actually don't necessarily need to worry about sanitation - Discord slash commands [provide a way to specify a finite number of options](https://discordjs.guide/interactions/slash-commands.html#choices). We could have the bot read from a DB something of the form
```json5
{
    choice: "Hub",
    url: "https://css.uwindsor.ca/hub"
}
```
then turn that into an array of options easy enough. Then its just a matter of procedurally handling the options (should be very easy as well)
