### ISSUE TITLE
Add the ability to delete Equation responses

### ISSUE THREAD

**Issue by kilbouri** [uwindsorcss/css-discord-bot#62]
#### Describe Problem

Currently, the bot just sends a rendered LaTeX equation. Because Discord escapes backslashes, its very common for people to need at least two attempts to render what they're after (the first where they don't know about backslash escapes, and the second where they realize their mistake and fix it).

#### Suggest Solution

Two possible solutions:

1. Add a subcommand like `/equation delete` which deletes the bot's most recent equation render for a user. Care will have to be taken to ensure that the bot never deletes a render it did for another user (ie, ensure user **A** running `/equation delete` doesn't result in user **B**'s render being deleted if user **B** used `/equation` after user **A**).
2. Add a button beneath every render that deletes the render. Ensure only the user who requested the render can delete the render.

1 has the benefit of not having a huge button under the render. 2 has the benefit of being easier to code and probably more user friendly.

#### Additional Details

If we wish to take option 2, its likely we will need to store info in a DB so that someone can go back to the render and delete it at any time. 

For a rough approximation of what an implementation of 2 would look like, see [the WinHacks 2022 bot](https://github.com/WinHacks/2022-bot). Most notably:
- [an example button event dispatcher/event receiver](https://github.com/WinHacks/2022-bot/blob/main/src/events/buttonEventHandler.ts)
- [an example button event handler](https://github.com/WinHacks/2022-bot/blob/main/src/events/buttons/invite.ts)

**Comment by BorhanSaflo** [comment]
Implemented in cd31684e4dc3ab6532bad96ec51e6732cb190639
